### ISSUE TITLE
Support for left/right swipe

### ISSUE THREAD

**Issue by shirishp** [darenju/react-flip-page#1]
Along with up / down swipe, it would be great if we can support left / right swipe.

**Comment by darenju** [comment]
[Done!](https://github.com/darenju/react-flip-page#props)

Thank you for the idea.

**Comment by shirishp** [comment]
This is amazing. Thank you so much. :)

**Comment by darenju** [comment]
Did you have time to try this feature? I'd like some feedback, if there are things to improve.

**Comment by shirishp** [comment]
@darenju I am building a magazine like site with React. Before this, we were using Turn.js. I wanted to use this library but it was missing swipe left/right. So I will try to use this library now. Will keep you posted. :)

Again, thank you very much for your efforts and quick response.
