### ISSUE TITLE
Keeping track of current page from outside the component

### ISSUE THREAD

**Issue by piaaaac** [darenju/react-flip-page#10]
Is there a way to keep track of the current page from outside the component? I mean independently from if pages changed by gesture or from with `gotoPreviousPage()` or `gotoNextPage()` methods.
Maybe the possibility to pass a callback that's executed on page change could do the trick? 
Or maybe there's a way already that I can't see...

**Comment by darenju** [comment]
It has been done. Check out PR #11. :smile:

**Comment by piaaaac** [comment]
Perfect !! Thanks a lot for the quick response
