### ISSUE TITLE
The onPageChange event is not fired when gotoPage(N) is called

### ISSUE THREAD

**Issue by kkomelin** [darenju/react-flip-page#100]
Hi there,

I have noticed that `gotoNextPage()` and `gotoPreviousPage()` trigger `onPageChange` event but `gotoPage(N)` does not.
Is it a feature or a bug?

Thanks,
Konstantin

**Comment by darenju** [comment]
Simple oversight from me.

Added it in `1.5.5`.

Thanks for reporting, @kkomelin.

**Comment by kkomelin** [comment]
Thanks @darenju. Tested. It's functioning properly now.
