### ISSUE TITLE
Demo on Codepen

### ISSUE THREAD

**Issue by strarsis** [darenju/react-flip-page#102]
I mainly want to use this component for the flipping effect and for turning pages on a traditional website.
It doesn't seem to be possible to make it running as demo on Codepen, see https://codepen.io/strarsis/pen/JzVGmW:
````
index.js:8 Uncaught ReferenceError: process is not defined
    at index.js:8
(anonymous) @ index.js:8
index.js:1 Uncaught TypeError: Cannot read property 'PureComponent' of undefined
    at index.js:1
    at Module.<anonymous> (index.js:1)
    at n (index.js:1)
    at index.js:1
    at index.js:1
    at index.js:1
    at index.js:1
````
`react`, `react-dom`, `prop-types` and `react-flip-page` have been added as external resources using `unpkg`.

**Comment by darenju** [comment]
Hello,

Thanks for pointing that out. Thing is, `process` is never used in `react-flip-page` codebase.

However, @kkomelin managed to make it run in CodeSandbox, you can try it on a sample URL he shared on #98: https://codesandbox.io/s/1z1pkoz903

That should fit your needs, I guess.
