### ISSUE TITLE
Paper-like effect

### ISSUE THREAD

**Issue by strarsis** [darenju/react-flip-page#103]
Currently all pages are like hardcovers/very stiff paper.
[turn.js](https://github.com/blasten/turn.js/) got also an effect [for soft, waving paper](https://github.com/blasten/turn.js/blob/master/turn.js#L1192).
Is it possible to implement this, too, ideally for the pages in between as usually in the real world?

**Comment by darenju** [comment]
As the introduction of `react-flip-page` suggests, this component just mimics the Flipboard® page turn effect.

So this will not make it in `react-flip-page`.

**Comment by strarsis** [comment]
@darenju: OK, but couldn't the scope be a bit changed so it also supports paper? 😸

**Comment by darenju** [comment]
No, the scope will not change.

The goal is to keep the package as small and feature-focused as possible.
