### ISSUE TITLE
Flipping not working correctly on IOS Ipad/Iphone

### ISSUE THREAD

**Issue by roniash101** [darenju/react-flip-page#104]
*A video which shows the bugs is attached.
[react-flip-page-bugs.zip](https://github.com/darenju/react-flip-page/files/3016721/react-flip-page-bugs.zip)

**Description**
When flipping left-to-right, before the page is changed, half of the page is hidden by the previous page for a second and only than the rest of the page appears.
Another problem is that when flipping (again on Ipad/Iphone), fixed elements with high z-index (In the video, the Home icon) are hidden by the pages until the flipping is over.

**Comment by darenju** [comment]
Hello, I see you are using images on your project. What we see is probably the loading time for the image. You should try reducing their weight as much as possible (using tinyjpg or such), to avoid that flickering effect. 

As for the home icon, you could use a bigger `z-index` if you want it always on.

**Comment by roniash101** [comment]
Hi, first, thanks for answering!

About both of the bugs - we're using the same code in Android and it works perfectly there, so it's unique to IOS for some reason..

We have already reduced the size of the images and it didn't solve the problems, and I'm actually not sure it has something to do with the loading time of the image cause it only happens when flipping backwards in the English version (which means the images should already be loaded, no?), and when flipping forwards in the Hebrew version (Hebrew is written right-to-left), which means the problem is always with left-to-right swiping.

About the second bug - we're already using `z-index: 15` and `position: fixed`.

**Comment by darenju** [comment]
Do you have the same problem if you use `vertical` as `orientation`? This could help me isolate the issue

**Comment by roniash101** [comment]
We tried `vertical as orientation`, and this is what happend: (the images are still `orientation horizontal`, but the flipping is vertical).

[vertusal_orientation.zip](https://github.com/darenju/react-flip-page/files/3026571/vertusal_orientation.zip)

By the way, this `orientation vertical` behavior happens also with Android and not just with IOS.

**Comment by roniash101** [comment]
Do you have any idea how can we solve that?

**Comment by darenju** [comment]
What you are showing is very weird. You seem to have the `showHint` enabled, we can see it at the beginning of the video. However, only half of the page is moving.

Would you mind showing some code?

Also, would you have any conflicting CSS with the component?

**Comment by roniash101** [comment]
Hey! We think that we have spotted the problem. After playing with the inspect elements, we noticed that changing the `rotateY(180deg)` of the 2ndChiled of the 3rdChiled  of the `div` with `role: presentation` and `display: block`, to `rotateY(-180deg)` fixes the bug: 

> When flipping left-to-right, before the page is changed, half of the page is hidden by the previous page for a second and only than the rest of the page appears.

Now we're trying to implement this to the code. If you could help us with some direction or instructions it will be great.

**Comment by darenju** [comment]
Hey,

It’s cool you seem to have found origin of the issue. If you feel like making a PR, please clone the repo then work on a separate branch, for clarity reasons. Other than that, if it is in the presentation part, you should take a look at the `renderPage` method (line 456 as of now).

**Comment by roniash101** [comment]
And about the code you asked: 
This is our FlipPage component:
` <FlipPage
                    className={this.t("swipeClass")}
                    responsive={true}
                    ref={(component) => { this.flipPage = component; }}
                    orientation="horizontal"
                    reverse={this.t("reverse") === "true"}
                    showSwipeHint={this.pageIndex === 0 && storyNavigationLen === 1 && this.state.enableSwipe}
                    onStartPageChange={this.onStartPageChange}
                    onPageChange={this.onPageChange}
                    disableSwipe={!this.state.enableSwipe}
                    flipOnTouch={!this.state.enableSwipe}
                    flipOnTouchZone={0}
                    startAt={this.pageIndex}
                    firstComponent={<img src={backgroundPattern} style={{ height: "100vh", float: "right" }} />}
                    lastComponent={<img src={backgroundPattern} style={{ height: "100vh", float: "left" }} />}>
                    {this.state.pages.map((page) => {
                        return <article key={Math.random()}>{page}</article>;
                    })}
                </FlipPage>`

And these are our event handlers:

` onPageChange = (pageIndex, direction) => {
        // Add case of refresh
        UserLocalStorage.setChoiceButtonClicked(false);

        if (this.StoryAudioController !== null && this.StoryAudioController) {
            this.StoryAudioController.stopStory();
        }
        else {
            console.log("NOTE: this.StoryAudioController = null/undefined");
        }

        if (!UserLocalStorage.ifCurrentPageIsSpecial()) {
            this.playStoryAudio();
        }

        // Prevents double calls
        if (!(pageIndex === 0 && direction !== "prev")) {

            let pageNum = UserLocalStorage.getPageNum();
            if (direction === "prev")
                pageNum -= 1;
            else
                pageNum += 1;
            UserLocalStorage.setPageNum(pageNum);
            window.history.pushState('page2', 'Title', `/#/kindergarten-friends/pages/${pageNum}`);

            this.removeNecessaryPages();
        }
    }

    onStartPageChange = (oldPageIndex, direction) => {
        let pages = [...this.state.pages];
        let storyLengthIndex = pages.length - 1;
        let addition = 1;
        let nextNav = UserLocalStorage.getNextPageNav();
        let currentPageIndex = -1;

        if (nextNav && (nextNav.includes("split") || nextNav.includes("otheroption") || nextNav.includes("conclusion") || nextNav.includes("end"))) {
            addition = 0;
            currentPageIndex = oldPageIndex + addition;

            if (direction === "next") {
                this.pageIndex += 1;
            }
            else {
                this.pageIndex -= 1;
            }
        }
        else {
            addition = (direction === "next") ? 1 : -1;
            currentPageIndex = oldPageIndex + addition;
            this.pageIndex = currentPageIndex;
        }
        let remaining = storyLengthIndex - currentPageIndex;

        let additionalState = {};

        if (direction === "next") {
            if (remaining) {
                this.loadPages.updateNextNav();
            }
            else if (this.state.lastPage) {
            }
            else {
                this.loadPages.updateNextPage(this.otherOptionInfo);
            }
        }

        if (direction === "prev") {
            if (this.state.lastPage) {
                additionalState = {
                    ...additionalState,
                    lastPage: false,
                };
            }
            this.loadPages.updateLastPage();
        }

        let enableSwipe = direction === "prev" ? false : this.state.lastPage;
        this.setState({
            ...additionalState,
            enableSwipe
        });
    }`

**Comment by roniash101** [comment]
Unfortunately, apparently it was not the problem and we are still stuck :(

**Comment by roniash101** [comment]
Hey, we don't really understand how, or what we did for it to happen, but the problem somehow got solved!!!

**Comment by darenju** [comment]
Great!

Closing this then.
