### ISSUE TITLE
Changing Background Color

### ISSUE THREAD

**Issue by AKluger** [darenju/react-flip-page#105]
Hi, I have written a children's picture book with text rendered underneath the images.  In attempting to alter the background color, I have applied one using style={bookStyle} much like you have utilized {endStyle} in your demo, and though upon inspection in devtools the background color on the Flip Page div is computed, it still shows up white.  I understand that there are actually multiple divs overlapping, but I am not seeing this new color anywhere.  Could you explain what I am missing or add walk-thru in the demo?  Thanks!

**Comment by darenju** [comment]
Hey, did you miss the `pageBackground` property?

**Comment by AKluger** [comment]
ugh apologies..  works as intended and thank you for the quick response.

**Comment by darenju** [comment]
No worries!

I’m thinking about showcasing the component, would you agree to give a link to an online usage of it?

**Comment by AKluger** [comment]
Hey I would absolutely be willing to share, however as you will see from
this link I am still struggling with the responsiveness.  Currently in
larger desktop windows the text is cut off and the book zoom further in the
image as you enlarge the window.  But here it is, a book for young children
about cleaning up their neighborhood:

https://winc-stories.herokuapp.com/prettybooks
