### ISSUE TITLE
Issue: Two-sided video

### ISSUE THREAD

**Issue by kkomelin** [darenju/react-flip-page#106]
### Problem

A video fragment from Youtube posted on a page are split into two pieces which can play independently of each other.

### Environment

```json
"react-flip-page": "1.5.7"
```

**Settings:**
```json
{
      orientation: "horisontal",
      responsive: true,
      uncutPages: false,
      animationDuration: 350,
      treshold: 3,
      pageBackground: "transparent"
}
```
**Browsers:**
- Chrome
- Firefox

**Code example:**
https://codesandbox.io/s/0xq9l37p1w

### How to reproduce

Open this demo https://0xq9l37p1w.codesandbox.io/ and try to play the video on the first page. You will see that only one half of the video actually plays.

### Additional notes
- I think it happens because react-flip-page creates two pages which lay one on top of another, so using exclusively static content can be an architectural limitation of the package but I still hope to find a workaround.
- If using exclusively static content is an architectural limitation of the package, it may be fair to inform users about it through the README.

Please let me know if you have any ideas on how to fix the issue.

**Comment by darenju** [comment]
Hey,

You're right about your assumption: since the pages are cut in half, when using non-static content, only one part will be reflected.

In the particular case of a video, maintaining the two parts in sync could be very tricky, as you would hear the sound twice.
I think I will add a warning on the README page.

**Comment by kkomelin** [comment]
Hey Julien,

Thank you for your prompt response and the information. You're demonstrating a great support approach.

Yes, I have to agree that playing two parts in sync would be a tricky task but thanks for the idea.
I had another idea to forcefully open fullscreen mode on click but in that case user would anyway notice the difference between two parts when she would come back from fullscreen.
So now I probably need to develop my own flip page component with limited functionality and with some workaround for this issue. It can be just one half of a book like in the Steller mobile app.

Found a notice on this issue in the README. Thanks for adding it.

Best,
Konstantin
