### ISSUE TITLE
When using swipeImmune, there is an error that says "index.js:1 Uncaught TypeError: this.props.swipeImmune.some is not a function"

### ISSUE THREAD

**Issue by stacygohyunsi** [darenju/react-flip-page#112]
This is how I am using the swipeImmune attribute: 
<img width="713" alt="Screenshot 2019-07-21 at 9 51 51 PM" src="https://user-images.githubusercontent.com/10786795/61592142-c6194380-ac01-11e9-96ba-c08cf1e18842.png">

But I seem to get the error: "index.js:1 Uncaught TypeError: this.props.swipeImmune.some is not a function"

And all of my pages seem to be unable to flip. 

Thank you!

**Comment by darenju** [comment]
This is not how you should use this prop.

Rather like:

```
<FlipPage swipeImmune={['.sel']} />
```

**Comment by stacygohyunsi** [comment]
Thanks @darenju, I tried writing it that way, but it seems like i still can swipe to flip the element:/

**Comment by stacygohyunsi** [comment]
![image](https://user-images.githubusercontent.com/10786795/61767812-03efb500-ae18-11e9-9299-ac143e184f03.png)

**Comment by darenju** [comment]
The `swipeImmune` prop is not supposed to work on the the first children of the `FlipPage` component (i.e. the "pages").

It is instead used to prevent swipes on elements such as buttons and such. So, it is normal that the `swipeImmune` still allows you to swipe from your first page. If instead you wanted to disable swipe, you could use the `disableSwipe` prop.

**Comment by stacygohyunsi** [comment]
I see, is there anyway to disableSwipe only for the first page?

**Comment by darenju** [comment]
Yes, just use a conditional:

```
<FlipPage
  disableSwipe={isOnFirstPage}
  onPageChange={this.pageHasChanged}
/>
```

You need to create a `pageHasChanged` callback, and set your `isOnFirstPage` value accordingly. 

This shows the component would need a `getCurrentPage()` method…

**Comment by stacygohyunsi** [comment]
Thanks so much @darenju!
