### ISSUE TITLE
onPageChange()

### ISSUE THREAD

**Issue by etacalpha** [darenju/react-flip-page#116]
Unless I have done something wrong I believe the parameters are backward.

```
onPageChange={(direction, index) => {
                console.log(
                  "this is direction",
                  direction + " this is index",
                  index
                );
              }}
```
When I change the page the console reads " this is direction 1 this is index next"

**Comment by darenju** [comment]
Hello,
Doc and code say the same thing: it’s index then direction. You get a `set` direction when using `gotoPage` method.
