### ISSUE TITLE
How can I hide the page shadowing?

### ISSUE THREAD

**Issue by Susan123456789** [darenju/react-flip-page#118]
I am creating a flip book with a front and back cover.  I have managed to do this by creating a transparent div that lives on the first half of the page.  It looks great, except that when you go to turn the first page, the page shadowing appears over my transparent div.  How can I eliminate this page shadowing effect?

```
<FlipPage
    uncutPages  = {true}
    orientation = "horizontal"
    width       = {flipbookWidth}
    height      = {flipbookHeight}
    maxAngle    = {0}
    pageBackground = "none"
    maskOpacity = {0}
    perspective = "260em"
    >
    <div className="d-flex flex-row">
        <div className="half-width">&nbsp;</div>
        <Page pageNumber={1} width={flipbookWidth/2} />
    </div>
    <div className="d-flex flex-row">
        <Page pageNumber={2} width={flipbookWidth/2} />
        <Page pageNumber={3} width={flipbookWidth/2} />
    </div>
</FlipPage>
```

**Comment by Susan123456789** [comment]
Hmmm, when I get to the last page if I use a transparent div for the right half of last page (because we are supposed to be looking at the back cover) then I can see another page underneath.  Is there a way I can hide that page???

**Comment by darenju** [comment]
Do you have a screenshot of what you are seeing? It would make it easier to help you eliminate that.

**Comment by Susan123456789** [comment]
Shadowing on first invisible page when turning the page:
![screenshot1](https://user-images.githubusercontent.com/49492073/67313334-ce1ea300-f4d0-11e9-8384-e7223ab09074.png)

Third page appearing under invisible last page:
![screenshot2](https://user-images.githubusercontent.com/49492073/67313335-ce1ea300-f4d0-11e9-9c18-2e4f6096e787.png)

**Comment by darenju** [comment]
For the second problem, you should use a white background in order to hide the invisible last page.

As for the shadow, there is no option currently. I will add one to disable those shadows.

**Comment by darenju** [comment]
Hey @Susan123456789 , I added a `noShadow` property on the component in its `1.6.0` version.

You should use it as shown:

```jsx
<FlipPage noShadow>
  {/* ... */}
</FlipPage>
```

**Comment by Susan123456789** [comment]
Thank you very much!!!!!
