### ISSUE TITLE
Issue: Input fields and drop-downs do not work

### ISSUE THREAD

**Issue by HiggsWRX** [darenju/react-flip-page#120]
Hey so yeah pretty much what the title describes. I am experimenting some things and what I have currently is a couple pages and on the last one I have a few input fields and dropdowns to submit a form. When the forms component is inside the FlipPage component the input fields and dropdowns  are unsuable.

Currently on "react-flip-page": "^1.6.0", tried in the chrome, chromium, and firefox versions. 

And by the way, thanks for the component, I love its simplicity while still looking amazing.

**Comment by darenju** [comment]
Hey, did you try the `swipeImmune` prop?
