### ISSUE TITLE
Could not find declaration for Module 'react-flip-page'

### ISSUE THREAD

**Issue by LuthfanM** [darenju/react-flip-page#121]
Hallo.

I feel like my question is really basic. But already try every solution from google but nothing works.
I am using expo and when i 'npm install react-flip-page', node_modules folder is not updated.
Thats why when i import package, it not detected. Using require similar output. Nothing works.

I am using 
react-native-cli: 2.0.1
react-native: 0.59.10

what the cause of the problem actually? i install other package such as react-native-map and its working just fine. 
Please help.

**Comment by LuthfanM** [comment]
Ok. Turn out this issue is produced by react cannot manage to find Variable 'Document'.
What cause of this actually?

**Comment by darenju** [comment]
`react-flip-page` is for Web. You need to use `react-native-flip-page`, which basically works the same.

You can find it on my profile.
