### ISSUE TITLE
Using on Mobile devices gives unexpected black background

### ISSUE THREAD

**Issue by addisonschultz** [darenju/react-flip-page#137]
This package is really great, I've even extended it quite a bit in Framer: https://packages.framer.com/package/addison/pagination

Using this on mobile gives weird behavior to the pages when flipping, as there is a black box coming from nowhere.

CodeSandbox: https://mbqir.csb.app/ (works as expected on desktop, not on any mobile device broswer)

Tested: iOS 13.5.1 Safari/Chrome

**Comment by darenju** [comment]
Hello,

That should be working with `v1.6.2`. Can you please check?
I updated the way to display gradients over pages to show the move…

**Comment by addisonschultz** [comment]
Look like it's working 🙌 

Apologies, when I installed the dependency in the top example, it installed `1.6.1` still. Not sure why, but can verify `1.6.2` is working as expected. Thank you!
