### ISSUE TITLE
Background Color Split in two for Span when it sits Between Pages

### ISSUE THREAD

**Issue by zoverlvx** [darenju/react-flip-page#140]
Love your library.

I'm currently having a weird bug where the background color of a word on the page won't fully highlight when hovered over when that word is specifically in between the two pages (I believe the "presentation" divs). Half of the word will highlight while the rest of it remains un-highlighted on the next page. I believe "pointer-events: none" might be the fix, but I'm not entirely sure.

https://github.com/zoverlvx/staging.langlib.xyz/blob/pagination/client/src/App.js

**Comment by darenju** [comment]
Hey!

Nope, this is due to the fact that the pages are actually split in halves. What I’d recommend, is to use a state property that holds if your `span` is hovered. You would update the render of your page, making it visible on the other half of the page.

**Comment by zoverlvx** [comment]
C'est ça! Merci, monsieur.
