### ISSUE TITLE
Pages blank until after flipped

### ISSUE THREAD

**Issue by saricden** [darenju/react-flip-page#143]
Hey there, encountering an issue with `react-flip-page`.

My render code is as follows:

```
<div className="view read-story">
  <FlipPage responsive={true} orientation="horizontal">

    <div className="book-title">
      <div>
        <p>Stuff on the left.</p>                  
      </div>

      <header className="story-title" style={{
        backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.75)),url(${storyData.smallCoverURL})`
      }}>
        <h1>{storyData.title}</h1>
      </header>
    </div>

    {
      lrPages.map((lr, i) => {
        return (
          <article key={"p"+i} className="book-page">
            <div>
              <p>{lr.l}</p>
            </div>

            <div>
              <p>{lr.r}</p>
            </div>
          </article>
        );
      })
    }

  </FlipPage>
  
</div>
```

The flip effect works perfectly, except that when navigating between any of the `lrPages` (the `<article>` tags), they are blank until the user releases the page and the animation completes, at which point the content for the page appears.

Anyone seen anything like this before? Thanks!

**Comment by saricden** [comment]
Update:

I think I've zeroed in on the problem. It appears the `.map()` function is throwing it off, because instead of returning JSX elements directly as children, it returns them as an array of children, which seems to be where the bug is coming from.

**Works:**
![works](https://user-images.githubusercontent.com/7004280/92397163-29eb1e00-f0db-11ea-82d6-237c70da4520.png)

**Doesn't work:**
![no-works](https://user-images.githubusercontent.com/7004280/92397258-63238e00-f0db-11ea-994b-4575714fb65f.png)

**Comment by darenju** [comment]
I have merged your PR and have published a new version of the package `1.6.3` that contains your fix.

Can you please confirm it works with this version?

Thank you!

**Comment by saricden** [comment]
@darenju On it :+1:

**Comment by saricden** [comment]
Hey @darenju I installed version `1.6.3` via `yarn add react-flip-page` but it appears the `node_module` directory doesn't contain the `dist` directory, so when I boot up my app it throws:

```
Module not found: Can't resolve 'react-flip-page' in '...'
```

Is this something on your end?

**Comment by saricden** [comment]
If I copy over the `dist` directory to `node_modules/react-flip-page` all is well.

**Comment by darenju** [comment]
Sorry, I had forgotten to `build` before publishing. `react-flip-page@1.6.4` should work normally.

Also, there are the tests to fix because of the addition of `.flat()` :
```
TypeError: this.props.children.flat is not a function
```

But this shouldn’t be a problem when installing.

**Comment by saricden** [comment]
@darenju Awesome, you're the man! Thanks for fixing the tests :shipit:

**Comment by saricden** [comment]
Works perfect in my implementation! :beers:

**Comment by darenju** [comment]
And thank you for reporting & fixing this issue you found. It helps the component get better!

**Comment by saricden** [comment]
:+1: My pleasure, this component has been hugely helpful for me on the app I'm working on!
