### ISSUE TITLE
Position of "middle of page"

### ISSUE THREAD

**Issue by TheShashank** [darenju/react-flip-page#146]
Hi there!

This is an awesome library, thanks so much for working on it! Quick question: I can't seem to be able to change the position of the middle of the page, the place where the black crease appears. Would it be possible for me to modify it so that the appearance is that there is only one large page (as opposed to two small pages divided by the black line during a page flip)?

Thanks!

**Comment by darenju** [comment]
Hello,

Thanks for the appreciation. 😄 
However, the whole point of this component is to mimic the Flipboard effect. It would not make sense to move the crease somewhere else. I would recommend you use something like (StPageFlip)[https://nodlik.github.io/react-pageflip/] instead.
