### ISSUE TITLE
Fragments

### ISSUE THREAD

**Issue by shashank2000** [darenju/react-flip-page#147]
So I've been trying for a while now to use React Fragments with this library, essentially I have a function that returns a bunch of `<article>stuff that goes into the page</article>` React elements (pages) - and I'd like for this to be displayed in another component, where the `FlipPage` component is actually defined. When I look into the dev inspector, it seems like what's actually happening is `<FlipPage> <div> <article/> <article/> <article/> </div> </FlipPage>`, which is making all the `article`s appear in the same page - not what I'd like. 

Is there something fundamentally wrong with my approach/is this possible with the library as it stands today? Happy to make a PR if this is something that needs to be added. 

Thanks!

**Comment by darenju** [comment]
I think your approach might be wrong. If you don’t mind showing a bit of code, we could try to find a solution.

My guess is that you are rendering those articles from an array or something similar. Then you don’t need to use a `Fragment` to render all the articles. Otherwise, the `FlipPage` component would only receive one child, which is the `Fragment`, and then it will clone it to add some props, thus making it into a `div`.

**Comment by shashank2000** [comment]
@darenju thanks for the reply! Yeah absolutely, so I have 
`<FlipPage orientation="horizontal" pageBackground="#a0abb0" loopForever="true" showTouchHint="true" showHint="true" showSwipeHint="true" class="flipper" height="800" width="1280" uncutPages="false">
        <RenderMessages message_file="./messages/message_4.json" start="1584073823022" end="1584111931950" />
</FlipPage>` 
in the parent component. And then in the RenderMessages component, this is my render function:

`render(){
    return (
      <>        
        {this.state.data ? this.relevant_messages() : <span>Loading...</span>}
      </>
    );
  }`

And lastly what the `this.relevant_messages()` function returns is another Fragment:
`return (
      <>
        {table_pairs.map(item => (
        <article>{item}</article>
        ))}
      </>
    )`
where regardless of the actual contents of the table_pairs array, I'd expect there to be one page per element of that array.

**Comment by darenju** [comment]
Yes, the key is to give `FlipPage` an array of components.

**Comment by shashank2000** [comment]
> Yes, the key is to give `FlipPage` an array of components.

Awesome, that did it thank you!
