### ISSUE TITLE
Failed prop type: e: prop type `children` is invalid; it must be a function, usually from React.PropTypes.

### ISSUE THREAD

**Issue by anuragedushire** [darenju/react-flip-page#22]
I am getting two warnings -

Warning: Failed prop type: e: prop type `children` is invalid; it must be a function, usually from React.PropTypes.
    in e

and

warning.js?6327:35 Warning: e: type specification of prop `style` is invalid; the type checker function must return `null` or an `Error` but returned a function. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).

Looking at the code, I see -

```
FlipPage.propTypes = {
  children: PropTypes.Children,
  ...
  style: PropTypes.shape,
  ...
```

Is this intentional?

**Comment by darenju** [comment]
Hello,

Thank you for reporting this problem I had not seen. No, this is definitely not intentional, I will work on it as soon as possible.

**Comment by darenju** [comment]
@anuragedushire This has been fixed.

**Comment by anuragedushire** [comment]
Thanks for a quick fix!
