### ISSUE TITLE
[feture-request] Flip pages with "touch" gesture

### ISSUE THREAD

**Issue by enikolas** [darenju/react-flip-page#25]
**As a** user of your lib, **I want** to be able to flip accross the pages using touch/click, **so that** I can have a similiar behavior of ereaders as Kindle, Kobo, and so on.

## Acceptance Criteria

- Allow the user to go to the **next** page with a simple touch/click, on the:
	- Horizontal oriented: **right**
	- Vertical oriented: **bottom**
- Allow the user to go to the **previous** page with a simple touch/click, on the:
	- Horizontal oriented: **left**
	- Vertical oriented: **top**
- It might work together with the actual swipe gesture, unless it is disabled by props.

**Comment by darenju** [comment]
Are you working on this, @enikolas? Or do you want me to take care of it?

**Comment by enikolas** [comment]
you can work on it! no worries.

I'm setting up the unit tests, as well as a code clean up (like remove the dist/ dir from git, as it is generated code... and so on)

**Comment by darenju** [comment]
The `dist/` dir is needed on Git, as it is the imported package. :)

**Comment by enikolas** [comment]
Oh, and if you don't mind, I would like to set up TravisCI and some NodeJS code analysis bot to improve the process:

- Greenkeeper: automatically update node dependencies and run the tests in the CI to check if it breaks anything
- Code climate: measures the code quality making use of numbers like Complexity/Simplicity, Readability, Maintainability, Repetition and Line-count-per-file...

**Comment by darenju** [comment]
Do everything you think might be good for the code quality.

I set up a Changelog file today, put some of the last changes in it.

**Comment by enikolas** [comment]
Like, about the ```dist/```, it not a good practice to check in generated code to git, or any other versioning system. 

A better approach is to generate the code (like the webpack bundle) in a CI and them deploy the package to npmjs from there (or even in your machine).

Here are some good practices detailed: [Best Practices for Node.js Development](https://devcenter.heroku.com/articles/node-best-practices#only-git-the-important-bits)

Right now I'm at work, when I get to home, I'll try to send a PR with the stuff I'm working there.

**Comment by darenju** [comment]
I didn't know CI could deploy the package to NPM. Good to hear.

I am grateful for the work you are doing on the repo, I will gladly check everything once you send the pr. 👍

**Comment by darenju** [comment]
This feature has been added in #29.

By default, the actual swipe gesture is disabled, unless the `flipOnTouchAllowDrag` property is specified.

Should it be the other way around? Should the swipe gesture still be allowed and maybe use `flipOnTouchDisallowDrag` property?

**Comment by enikolas** [comment]
I don't know. I gues you could let both be enabled and let the user use the gesture which better suits him.

My idea on this feature is to allow a good usability on multiple devices, like, phones, tablets, and computers, no mater the size of each device.

I do know that on computers, the swipe gesture is not that natural, so clicking to turn page is more natural and user friendly.  Maybe on mobiles, it works in the oposite way.

Something that we might need here is a ```showTouchHint``` animation for the touch gesture as well.

**Comment by darenju** [comment]
As of `0.13.0`, a few changes were made:

> ## 0.13.0
> ### Added
>
> - `showTouchHint` property that shows a pointer indicating where to click or touch to switch pages.
>
> ### Changed
>
> - `flipOnTouchAllowDrag` has been renamed to `disableSwipe`. By default, the swipe is always allowed with `flipOnTouch`, unless `disableSwipe` is specified.
> - `showTouchHint` has been renamed to `showSwipeHint` to avoid confusion.
> - Changed default `flipOnTouchZone` from `20` to `10`.

So this matches your expectations @enikolas. The swipe gesture is always enabled, unless specified otherwise with `disableSwipe`. I wrote a warning in the README, saying if you disable the swipe gesture you should provide another way to switch pages, such as `flipOnTouch` or buttons with `gotoNextPage()` methods.

**Comment by enikolas** [comment]
Sorry, I got busy these days.

I need to do some tests on how it will work on my project. But it seems pretty good.

Thank you al lot for implementing it!

I'm still on my way for the code coverage of your project. I have just sent you a PR with some test written down.

And I have asked you to enable `codecov.io` to display the code coverage at README page, given the proper **HOW-TO** on the PR description.

I guess after covering it at a reliable stage, then we should care about adding `code climate`, as it will guide you on good code practices and improve even more the quality of your project!

I hope I'm being useful to you, as much as your project is going to be useful to my project!

Cheers!
