### ISSUE TITLE
Support for uncut page flipping

### ISSUE THREAD

**Issue by bernatfortet** [darenju/react-flip-page#3]
When a page is being flipped the page 3Dness is cut by the container. I've tried messing around with the css and it's possible to deactivate one of the overflows to achieve the 3D effect

![image](https://cloud.githubusercontent.com/assets/390010/25720902/6c7a5d66-30c3-11e7-93db-4bf3742ca969.png)

![image](https://cloud.githubusercontent.com/assets/390010/25720987/bac5f70a-30c3-11e7-9478-153beb15d322.png)

**Comment by darenju** [comment]
Thank you for opening this issue.

This could be a feature controlled by a prop, as the default Flipboard behavior is to mask everything outside the container (which is basically the device screen).

We could use a property as mentioned before. How would we name it? `canFlipOutsideContainer`? Any idea would be appreciated :)

**Comment by darenju** [comment]
Hello,

I have added this feature to the project! Instead of the long `canFlipOutsideContainer`, I used the `uncutPages` property. When set to `true`, the effect is visible, but when set to `false` (the default value), the standard behavior applies.

Thank you!

**Comment by bernatfortet** [comment]
Awesome! Thanks
