### ISSUE TITLE
[feature-request] Responsive width and height

### ISSUE THREAD

**Issue by enikolas** [darenju/react-flip-page#31]
**As a** user of your lib, **I want** to be able to not specify the width, neither the height of FlipPage component, **so that** the component can have a dynamic size and fit any device screen.

## Acceptance Criteria

- Do not specify the width/height of the component as a required field.
- Make the component resizable thrown CSS styles with `media` breakpoints.
- Test how your component will render on different devices screen making use of [Google Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools/device-mode/)
- Test it in your personal device as well

**Comment by enikolas** [comment]
I plan to finish the coverage first. Once I have finish that, I can work on this. Unless if you want to start it by now, then fell free to do it!

**Comment by darenju** [comment]
I have improved code coverage a little bit. `generateStyles.js` is 100% covered, but it takes time to fully cover `index.jsx`. I prefer to work on the responsive part, even though this will probably take time too, as we need fixed dimensions for the CSS effect to work.

**Comment by enikolas** [comment]
Ok, you can work on this task then. 

And I'll focus on fully covering `index.jsx`.

**Comment by darenju** [comment]
Let's do that. Please rebase from `master` as I have updated code coverage a little bit.
