### ISSUE TITLE
README : onEndSwiping callback is onStopSwiping

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#40]
Hi,

In the readme we have onEndSwiping  but in the code it is in reality onStopSwiping.

Thank you

**Comment by darenju** [comment]
Thank you for reporting this issue, I will correct this mistake very soon!

**Comment by darenju** [comment]
[Fixed](https://github.com/darenju/react-flip-page/commit/96f87d287524fc181f5f1fcd5b3dcc18713c0ff3).
