### ISSUE TITLE
onPageChange behavior

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#41]
When I use onPageChange(pageIndex) I see that pageIndex is the previous page and not the page I went to.

For example : 
- move to page 0 to 1 --> got onPageChange(0)
- move to page 1 to 2 --> got onPageChange(1)
- move to page 2 to 1 --> got onPageChange(2)
- move to page 1 to 0 --> got onPageChange(1)

Is it the desired behavior ?

**Comment by darenju** [comment]
It is not supposed to be the desired behaviour. I will look into it.

**Comment by darenju** [comment]
[Fixed](https://github.com/darenju/react-flip-page/commit/e27b82287f876883619a52c5f9a8c01542a06b1e).
