### ISSUE TITLE
The components get rendered too much

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#42]
Hi,

I have noticed that the render method of my component in the FlipPage component get rendered very often, even pages that are not displayed : 
- on mouse enter/out the flip page
- on click on the page
- every move during the flip

I think this causes the appli to slow down, moreover it seems that the state of the sub component is not kept.

Some code : 
```
<FlipPage>
  <Page1/>
  <Page2/>
  <Page3/>
</FlipPage>
```

```
function Page3(props) {
        console.log('render page3')
        return ( 
        <div>
            <img className="pageBackground" src={require("./img/Page-03.png")} />
        </div>
        )
}
```
In this example, I have just move the mouse around the component and click on the first page, but the third page get rendered anyway :

![image](https://user-images.githubusercontent.com/18260229/38952366-42cf0e2e-4343-11e8-8a01-598fbc364fc7.png)

In an other example, I have a next button which is disabled by default and enabled by the some user action.

```
function noop(){}

function NextButton(props) {
    // We disable the click if not active
    const click = props.active ? props.onClick : noop;
    const className = 'animated ' + (props.active ? '' : 'inactive');
    console.log('render next button')
    return (
        <img id="page-next" className={className} src={require('./img/page_next.png')} onClick={click} />
    )
}
```

```
class Page1 extends Component {
    constructor(props) {
        super(props);
        this.state = {}
        this.handleClickBell = this.handleClickBell.bind(this)
      }

      handleClickBell() {
        this.setState({canGoNext : true })
      }

      render() {
       
        return ( 
        <div>
            <img className="pageBackground" src={require("./img/Page-01.png")} />
            <NextButton key='page01' onClick={this.props.onClickNext} active={this.state.canGoNext}/>
            <Bell onClick={this.handleClickBell}/>
        </div>
        )
    }
  }
```
There I have just move the mouse a little for a few seconds and I have hundreds of renders:
![image](https://user-images.githubusercontent.com/18260229/38952799-b6775b5a-4344-11e8-9349-e68d6eab6522.png)

**Comment by darenju** [comment]
Interesting, I am trying to make this work.

The idea would be that only the wrapper page would stop from re-rendering.

**Comment by slevy85** [comment]
Then I think it is a great idea.
What is the way you would implement it ?
I found in [SO](https://stackoverflow.com/a/31564812/6695569) some useful information about high order component that could be a solution for us.

**Comment by darenju** [comment]
This is exactly what is needed: a higher order component.

This is what I came up with:

```jsx
class FlipPageItem extends PureComponent {
  render() {
    return this.props.component;
  }
}
```

And usage:

```jsx
const pageItem = <FlipPageItem
  shouldUpdate={activeItem}
  component={_page}
/>;

const clonedBeforeItem = <FlipPageItem
  component={beforeItem}
  shouldUpdate={activeItem}
/>;
const clonedAfterItem = <FlipPageItem
  component={afterItem}
  shouldUpdate={activeItem}
/>;
```

This way, there are much less renders. Components still get rendered even though they are not visible at first: they must be rendered underneath current page.

I plan on releasing this today.

**Comment by darenju** [comment]
Hey @slevy85, you should try `react-flip-page@0.17.0` as I have implemented said change.

There are no useless renders on page components now: only when halves need to be displayed.

**Comment by slevy85** [comment]
Hi @darenju, thank you very much for this great work.

I don't see the package in npm: 
`npm ERR! notarget No matching version found for react-flip-page@^0.17.0`
Is it normal ?

**Comment by darenju** [comment]
There was a problem in travis build. This is fixed: `react-flip-page@0.17.2`

**Comment by slevy85** [comment]
Thank you it is working great, there is less renders and it feels faster.

**Comment by darenju** [comment]
Thank you for reporting this issue, it has helped the package improve performance.

Closing this now.
