### ISSUE TITLE
The state of a page is not reflected on the second half

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#44]
Hi,

This issue is related to [this one](https://github.com/darenju/react-flip-page/issues/42).

I have noticed that the state of my page is not reflected on every part of it but only in the half that changes the state.

For example, in a page I have a button 'go next' on the right, this button is disabled.
I have an other button which enables the 'go next' button when the user clicks on it. If this button is in the same side of the 'go next' button, the button gets enabled correctly. But if it is in the other side, the button stays disabled.

I think this is because of the use of React method `cloneElement`. Which duplicates the element props, but when the state of the first one changes, it doesn't go to the second one.

I don't how this could be fixed, do you have an idea ?

Thank you for your help

**Comment by darenju** [comment]
Hey,

I will take a look at your issues this weekend.

Thank you for reporting.

**Comment by darenju** [comment]
As you might have found it if you read the code, we need to split the page in two halves so that they can flip separately.

I am afraid there is no simple way to deal with what you are trying to do. Apart maybe to temporarily disable swiping on the component (via `disableSwipe` property) when you are dragging your bowl.

**Comment by slevy85** [comment]
I disabled the swipe completely and it doesn't work.
Is it possible to deal with it in css z-index ?
One of the half could be under the other one, so that we only interact with the original component and not the clone. I am not sure if it could works.

**Comment by darenju** [comment]
Even with swipe disabled, there would still need a clone as the two halves are always needed.

**Comment by slevy85** [comment]
Maybe it could be done with [render props](https://reactjs.org/docs/render-props.html) ?
But I am not sure how ...

**Comment by slevy85** [comment]
Hi,
What do you think about this issue ?

**Comment by darenju** [comment]
I’m afraid I won’t be able to give you a positive answer for this… This is a very specific use case, and the repo is somehow a showcase. It cannot cover all of the use cases.
