### ISSUE TITLE
Images are splitted in two

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#45]
Hi,

I already mentionned this in the issue about the state, but I think it is a different problem so I make an other issue.
When an image is inside a page on the middle it is splitted : 
![image](https://user-images.githubusercontent.com/18260229/39083520-10a705f2-455d-11e8-9141-9e027bcff219.png)

```
<FlipPage>
    <Page1>
</FlipPage>
```
Page1 :
```
render() {
        return ( 
        <div>
            <img className="pageBackground" src={require("../../img/Page.png")} />
            <Bowl id="page-bowl" />
        </div>
        )
    }
```

I have managed to make this work by removing the `bottom: 0px` on three divs : 
- the clonedBeforeItem
- the pageItem
- the clonedAfterItem

```
const noBottom = {bottom: 'unset'};

 <div role="presentation">
    <div style={m(part, before, cut, noBottom)}>
          {clonedBeforeItem}
          <div style={mask} />
        </div>
        <div style={m(part, cut, after)}>
          <div style={pull}>{clonedAfterItem}</div>
          <div style={mask} />
        </div>
        <div style={m(part, visiblePart, firstHalf, this.state.firstHalfStyle)}>
          <div style={face}>
            <div style={m(cut, firstCut, noBottom)}>{pageItem}</div>
            <div style={m(mask, maskReverse)} />
            <div style={m(gradient, gradientFirstHalf)} />
          </div>
          <div style={m(face, back)}>
            <div style={cut}>
              <div style={pull}>{clonedBeforeItem}</div>
            </div>
            <div style={m(gradient, gradientFirstHalfBack)} />
          </div>
        </div>
        <div style={m(part, visiblePart, secondHalf, this.state.secondHalfStyle)}>
          <div style={face}>
            <div style={cut}>
              <div style={pull}>{pageItem}</div>
            </div>
            <div style={m(mask, maskReverse)} />
            <div style={m(gradient, gradientSecondHalf)} />
          </div>
          <div style={m(face, back)}>
            <div style={m(part, after, cut, firstCut, noBottom)}>
              {clonedAfterItem}
            </div>
            <div style={m(gradient, gradientSecondHalfBack)} />
          </div>
        </div>
      </div>
```

This alignes the image, but it causes a shadow to appear on the bottom when swipping : 
![image](https://user-images.githubusercontent.com/18260229/39092429-aecfed0e-4605-11e8-8368-7224fff89388.png)

What do you think about this ?

**Comment by darenju** [comment]
Are you using a retina screen, or high DPI screen by any chance? I had noticed this slight shift on some cases. This is often due to the container height. Playing with it, adjusting it even by .5 pixels could solve the issue.

As you can see on the demo page, this problem is not present, because heights are defined properly.

If you are certain this doesn’t affect any other cases (i.e. causing shifting in cases where `bottom: 0;` was still defined), then this could be changed in the codebase.

**Comment by slevy85** [comment]
I am using these screen, but thank you pointed me to the right direction, it was about my css.
The image where position absolutely on that contained the flip page component, instead I positioned my image on a page that is inside the flip page component :  
```<div class="container">
       <FlipPage>
              <Page class="pageContainer"><img src="background"/><img src="otherImg"/>
              </Page>
       </FlipPage>
   </div>
```

**Comment by darenju** [comment]
So, is everything working correctly for you now?

I had tried to keep in mind every way people could use my component. Therefore, probably all of the CSS is useful. It still might not fit some edge cases, but as it's an open source project, forking is always possible.

Though this gives me the idea to add a `pageStyle` property that would be applied to all of the pages.

**Comment by slevy85** [comment]
Yes everything is working thank you, you can close the issue.
Yes it would be nice to have a className associated to every part of the page so we can customize it if necessary.

**Comment by darenju** [comment]
I will implement this then.
