### ISSUE TITLE
Elements with z-index greater than 0 are seen on the pages before and after

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#47]
Hey,

I have noticed that when an element on a page has a z-index > 0, I still see it when I turn the page.
Can you reproduce that ?
Do you have an idea how to correct it ?
Thank you very much.

**Comment by darenju** [comment]
Hello @slevy85,

This is because `react-flip-page` uses `z-index`s to correctly show current page and pages underneath.

Maybe `react-flip-page` should use bigger `z-index` on its pages? I'm not a fan of big (> 999) `z-index`, but the solution is here.
