### ISSUE TITLE
Page flipping back when mouse out

### ISSUE THREAD

**Issue by DimaBur** [darenju/react-flip-page#51]
I implemented simple demo from docs. 
I can flip page by mouse, but when I bring the mouse out of the component, page flips back. 
React: 15.6.2
Here is the [video](http://take.ms/lUoKY).

**Comment by darenju** [comment]
Weird behavior. There might be a problem with the `mouseout` event handler. I will look into this.

Thanks for reporting.

**Comment by darenju** [comment]
I can’t seem to reproduce this behavior on [the demo page](http://darenju.me/react-flip-page/examples).

Would you mind providing a sample repository?

**Comment by DimaBur** [comment]
It's very strange but it's reproduсeing not always, and I can't find conditions. But I found why its happens.

`src/index.jsx:372`

`mouseLeave() {
    if (this.props.flipOnLeave) {
      this.stopMoving();
    } else {
      this.reset();
    }
  }`

If remove `this.reset();` this bug will disappear, but `loopForever` prop will not work.

**Comment by mcarreon** [comment]
Was there any resolution to this bug? I opened a similar issue and just saw this post.

**Comment by ambarishpande** [comment]
@DimaBur @mcarreon I am facing the same issue. Do we have a work around for this ?

**Comment by mcarreon** [comment]
> It's very strange but it's reproduсeing not always, and I can't find conditions. But I found why it happens.
> 
> `src/index.jsx:372`
> 
> ```
> mouseLeave() {
>     if (this.props.flipOnLeave) {
>       this.stopMoving();
>     } else {
>       this.reset();
>     }
>   }
> ```
> If remove `this.reset();` this bug will disappear, but `loopForever` prop will not work.

This worked for me, still not sure what the repercussions are but it worked as intended.

**Comment by slevy85** [comment]
I am also experimenting this with version 1.2.2 and react 16.6.3, it works fine on 1.2.0.

**Comment by darenju** [comment]
If several people can confirm the bug disappears when removing the `this.reset()` in `mouseLeave` method, then I might remove it from code and release a new version.

**Comment by slevy85** [comment]
I have tried to use ` flipOnLeave={true}` and didn't change anything. Should it have the same effects than to remove `this.reset()` in the method ?

**Comment by slevy85** [comment]
> I have tried to use ` flipOnLeave={true}` and it didn't change anything. Should it have the same effects than to remove `this.reset()` in the method ?

**Comment by darenju** [comment]
> I have tried to use ` flipOnLeave={true}` and didn't change anything. Should it have the same effects than to remove `this.reset()` in the method ?

Do you mean the behavior of the component should change? Yes, it should. If you flip the page at least half of the way and the mouse goes out of the component, the page should flip if `flipOnLeave` is `true`.
