### ISSUE TITLE
Add a way to go directly to a page

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#54]
Hello,

I have a use case to implement where the user would click on a link in the begining of the book wich leads him to a specific page in the page.

I have tried to increment the page in a for-loop with `gotoNextPage()`, I am able to go to the wanted page but it makes every pages appear and swipe until the good page appears.
 
Is there a way to go to a page directly without showing every page ?

Stephane.

**Comment by darenju** [comment]
There is the `startAt` prop, but from what you wrote, I'm guessing you need this to be dynamic.

This would add a very simple method that would simply set the current page to another value.

**Comment by darenju** [comment]
@slevy85 I published `react-flip-page@0.18.0` introducing `gotoPage` method.

**Comment by slevy85** [comment]
Thank you very much for this !
