### ISSUE TITLE
onStartSwiping event is fired on a simple click

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#55]
Hi, 
I have noticed that the onStartSwiping event is fired on a simple click, it seems to me that it is too fast. What do you think if there was something like a threshold, the event is fired would be fired only if the users keeps his mouse down and mov a little bit ?

**Comment by darenju** [comment]
It could be triggered on the first time moving, true.

I'll work on that.

**Comment by darenju** [comment]
Done on `v1.1.0`.

**Comment by slevy85** [comment]
Thank you very much !

**Comment by slevy85** [comment]
Do you think it could be possible to use the treshold too ?
I mean that if the user uses a 50px treshold, the startSwiping callback would be fire when the users swipes 50px.
What do you think ?

**Comment by darenju** [comment]
Yes, we could use the `treshold` prop as defined on the component.

**Comment by darenju** [comment]
@slevy85 I implemented the change in `v1.2.0`.
