### ISSUE TITLE
Can't find variable : document

### ISSUE THREAD

**Issue by kyunkakata** [darenju/react-flip-page#59]
I stucked at this issue when i used FlipPage for my react-native app run on android device. Please show me how to fix this issue

**Comment by darenju** [comment]
Hello,

This package is *NOT* compatible with react-native. Please check out [react-native-flip-page](https://github.com/darenju/react-native-flip-page) instead. I just started developing it, only tested on iOS device. I will provide documentation soon.

Here is a basic sample code for it:

```
<FlipPage orientation="vertical">
  <FlipPagePage style={{ backgroundColor: '#fff', justifyContent: 'center', alignItems: 'center' }}>
    <Text>Page 1</Text>
  </FlipPagePage>
  <FlipPagePage style={{ backgroundColor: '#fff', justifyContent: 'center', alignItems: 'center' }}>
    <Text>Page 2</Text>
  </FlipPagePage>
</FlipPage>
```

**Comment by kyunkakata** [comment]
Thank you darenju. I will try react-native-flip-page
