### ISSUE TITLE
Trigger the effect outside the component?

### ISSUE THREAD

**Issue by niiapa** [darenju/react-flip-page#7]
Hello, thanks for the package.
I was wondering if there was any way to trigger the effect of flipping the page with something like a button outside the component. Thanks.

**Comment by darenju** [comment]
Hello @niiapa,

For now, there is no way to trigger a previous/next page effect outside of the component. I will think of a way to do it, but I must find something "react-compliant".

Thank you for the feedback.

**Comment by darenju** [comment]
Hey @niiapa, this has been implemented! Check out PR #8 and [documentation](https://github.com/darenju/react-flip-page/blob/master/README.md) for an example.

**Comment by niiapa** [comment]
Wow. Godsend! Thank you so much for the quick update!!!
