### ISSUE TITLE
Can't navigate with gotoPage to cover page

### ISSUE THREAD

**Issue by redferret** [darenju/react-flip-page#75]
It's very confusing that when I print out the index of page 1 it says 0. Even though we can't use `gotoPage(0)` as it throws an error, that page is indexed as 0. Going to page 1 technically goes to page 2. Can this be fixed?

**Comment by darenju** [comment]
Hello @redferret, sorry for not noticing your issue earlier.

This was a typing mistake in the condition of the `gotoPage` range check method. This should be fixed in `1.2.1`.
