### ISSUE TITLE
Between 1.2.0 and 1.2.2 mouse/click based turning broke

### ISSUE THREAD

**Issue by daaku** [darenju/react-flip-page#82]
Flipping pages with the mouse doesn't work, it's hard to explain besides saying that you need to try it. I noticed the examples at http://darenju.me/react-flip-page/examples are also using an older build and work right. Another data point is that it still works when using the `gotoPreviousPage` etc methods.

**Comment by yoavgurevich** [comment]
I can also confirm this is an issue for me with the latest update... Could this have anything to do with the `index.jsx` constructor missing a binding call for the two functions `goToNextPage` and `goToPreviousPage()`?

**Comment by darenju** [comment]
Hello,

This shouldn't have a link with the two methods missing a binding, as they are never called inside the code base if I'm not mistaken.
So are you saying the basic functionality is broken? That holding down the mouse button and flipping up and down doesn't switch pages anymore?

**Comment by daaku** [comment]
Yep, using the react 16.6.3 and react-flip-page 1.2.2 results in basic functionality being broken for me.

**Comment by darenju** [comment]
Hey @daaku, thank you for reporting this quick.

I have looked into the code base and actually, the `canAnimate` property was messing it up. It was effectively reset in the `reset` method, but its value wasn’t reset properly before animating the page switch. I have fixed this, and will now try to build with `react@16.6.3` to see if any side effects happen.

**Comment by darenju** [comment]
There should be a version `1.3.0` online soon with this bug fixed.

Please tell me @daaku when you have time to test it out.

**Comment by daaku** [comment]
Just tried it -- looks fixed like it's fixed -- thank you!
