### ISSUE TITLE
support right-to-left direction

### ISSUE THREAD

**Issue by slevy85** [darenju/react-flip-page#83]
Hi,

we already had this discussion here and you gave me a [solution](https://github.com/darenju/react-flip-page/issues/23#issuecomment-383165856), but it is not efficient in term of loading because we start loading the last page.
It happens because when I want them to be right to left, I reverse them in `<FlipPage>` component and use `startAt`  property to begin at the end.
The result is that the first page (which is the last one in `<FlipPage>`), is loaded at the end.

I will try to make a PR for this.

**Comment by darenju** [comment]
Hey! Thank you for this, I'll check the PR when you send it.

**Comment by darenju** [comment]
This feature has been merged thanks to @slevy85 and is now available in `react-flip-page@1.4.0`.

**Comment by slevy85** [comment]
Great, thank you very much
