### ISSUE TITLE
`flipOnTouch` Buttons do not work + Errors on swipe animations

### ISSUE THREAD

**Issue by yoavgurevich** [darenju/react-flip-page#86]
As of latest version 1.3.0 attempting to use the `flipOnTouch` option buttons does not work, at least with mouse clicks. I have left the rfpTouchZone property at its default value as well.

Second issue is that while swiping back and forth, these error stacks keep popping up intermittently:

![rpf_err_stack](https://user-images.githubusercontent.com/2465960/49699386-7ddf7080-fb9e-11e8-9a89-8df85779d372.png)

Here is my `package.json` for visibility as this may be a result of conflicting dependencies:

```
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "css-loader": "^0.28.11",
    "file-loader": "^1.1.11",
    "node-sass": "^4.8.3",
    "react-hot-loader": "^4.1.0",
    "sass-loader": "^7.0.1",
    "style-loader": "^0.20.3",
    "url-loader": "^1.0.1",
    "webpack": "^4.19.1",
    "webpack-cli": "^2.0.14",
    "webpack-dev-server": "^3.1.3"
  },
  "dependencies": {
    "font-awesome": "^4.7.0",
    "react": "^16.5.2",
    "react-dom": "^16.3.2",
    "react-flip-page": "^1.3.0",
    "react-scroll-to-component": "^1.0.2",
    "scrollmonitor-react": "^2.3.2"
  }
```

Let me know if I can provide anything else to be of further assistance. Thank you.

**Comment by yoavgurevich** [comment]
@darenju Thank you and sorry for the delay. The buttons are working perfectly as of the latest version but the error stacks above still occur intermittently. Here is the code I am currently using with flip-page:

```javascript
export default class ArticleFlipper extends Component {
    constructor(props) {
        super(props);
        this.state = {
            currentPage: 0
        }

        this.handlePageChange.bind(this);
    }

    handlePageChange(idx) {
        this.setState({currentPage: idx});
        if (this.props.resolveBg) {
            this.props.resolveBg('articleFlipper', idx);
        }
    }

    render() {
        if (this.props.resolveBg) {
            this.props.resolveBg('articleFlipper', this.state.currentPage);
        }

        return (
            <div className='container' ref={this.props.refsList.articleFlipper}>
                <FlipPage
                    orientation='horizontal'
                    className='flipContainer'
                    flipOnTouch
                    onPageChange={(idx) => this.handlePageChange(idx)}
                    pageBackground='transparent'
                    perspective='40em'
                    responsive>
                    <SubComponentA
                        currentPage={this.state.currentPage}
                        refsList={this.props.refsList} />
                    <SubComponentB
                        currentPage={this.state.currentPage}
                        refsList={this.props.refsList} />
                    <SubComponentC
                        currentPage={this.state.currentPage}
                        refsList={this.props.refsList} />
                    <SubComponentD
                        currentPage={this.state.currentPage}
                        refsList={this.props.refsList} />
                </FlipPage>
            </div>
        );
    }
}
```

The subcomponents simply return article tags and some conditionally rendered html content. The `resolveBg` function takes strings or the current page number (optional) and maps them to an array of background colors to transition to as the focus changes between components. I also have a window event listener that triggers this function on scroll. Relatively straightforward IMO, but let me know if you would like to see those as well.

**Comment by darenju** [comment]
This might probably not be related to anything you wrote in the component.

However I don’t quite see where the issue could come from in the `FlipPage` component… do you have any more specific action to do to show those error stacks? What you could do is download the source code of this project and use the `src/index.jsx` as import for `FlipPage` component. If the issue is `react-flip-page`-related, we would have a more convenient error log.

Thank you.

**Comment by darenju** [comment]
I think it is the second issue. It’s weird, I thought `pageX/Y` were supposed to work in any browser. Which version of Chrome are you using? I will add more checks on this part.

**Comment by yoavgurevich** [comment]
@darenju as of version 1.5.3 I can confirm all issues have been resolved, many many thanks! Please feel free to close the issue.
