### ISSUE TITLE
Flip page cut the buttons and video controls

### ISSUE THREAD

**Issue by hiteshsahu** [darenju/react-flip-page#91]
A full screen video or button control gets cut into half in horizontal swipe mode. Clicking on a full screen button will trigger click on half part of button while other half remains as it is thats weird.

https://codesandbox.io/s/5zw2wnknnl

<img width="1025" alt="screen shot 2019-01-09 at 16 44 26" src="https://user-images.githubusercontent.com/4076925/50910338-e6d03780-142d-11e9-8ce2-caa27509e2eb.png">

**Comment by darenju** [comment]
No info on this, closing.
