### ISSUE TITLE
Will This work with IE 11?

### ISSUE THREAD

**Issue by chobo2** [darenju/react-flip-page#95]
The example pages are not loading up in IE 11. will this plugin work with it?

**Comment by darenju** [comment]
It should work with IE11. But to be honest I am not supporting this browser.

**Comment by chobo2** [comment]
@darenju 

I wish I did not have to support it either. Do you know why this example page of yours is not working in IE11? http://darenju.me/react-flip-page/examples

I see no errors so not sure if it is your plugin or the example site.

**Comment by darenju** [comment]
The problem comes from the bundle, so it might just be because of babel. I might need to add some polyfills. I will check on that later on.

**Comment by chobo2** [comment]
@darenju 

That would be appreciated. Thanks.
