### ISSUE TITLE
Issue: Single touch causes double flip with flipOnTouch enabled

### ISSUE THREAD

**Issue by kkomelin** [darenju/react-flip-page#98]
### Problem

Single touch causes flip of two pages at once with flipOnTouch option enabled.

### Environment

```json
"react-flip-page": "1.5.3"
```

**Settings:**
```json
{
      orientation: "horisontal",
      responsive: true,
      uncutPages: false,
      animationDuration: 350,
      treshold: 3,
      pageBackground: "transparent",
      flipOnTouch: true
}
```
**Browsers:**
- Chrome mobile
- Chrome desktop (with mobile device emulation)
- Firefox (Responsive Design Mode)

**Code example:**
https://codesandbox.io/s/1z1pkoz903

### How to reproduce

Open this sandbox https://1z1pkoz903.codesandbox.io/ in one of the browsers listed above.
Touch right-hand edge of the page to turn it. You will see that it opens Page 3 instead of Page 2.

### Additional notes
- flipOnTouch works as expected on desktop browsers. 
- Swipe gesture works as expected on mobile and desktop.
- iPhone's Safari doesn't have this issue.
- I guess the issue can be related to a Google Chrome "intervention". Some time ago they forcefully converted event listeners to 'passive' which caused `e.preventDefault()` not working.
Try to remove `touchAction: 'none'` from my sandbox to see the corresponding warning in the console. More info https://www.chromestatus.com/features/5093566007214080

**Comment by darenju** [comment]
Hello,

Thank you for this very detailed issue. I will take a look at it this weekend as I am busy working on client project.

All of the details you provided should help me a lot to resolve this issue.

**Comment by kkomelin** [comment]
Thank you so much @darenju . And best of luck with your client project.

**Comment by darenju** [comment]
I think I have found what could cause the issue.

Version `1.5.4` was published, would you mind checking if the issue still persists?

Thank you.

**Comment by kkomelin** [comment]
Thank you @darenju for your efforts. Unfortunately, it still has the issue on touch devices.
I updated my sandbox to reflect the version change https://codesandbox.io/s/1z1pkoz903

**Comment by darenju** [comment]
I ended up giving up on touch events for the flip zones.

Now only the mouse events are present, but the flip zones should still work. Published a new version, `1.5.6`.

**Comment by kkomelin** [comment]
It seems like swipe stopped working on mobiles with flipOnTouch enabled. Tested in Chrome mobile emulator (aka responsive testing tool). I updated my sendbox.

A couple of thoughts:
- You don't have to release a new version just for me to test. We could work in a separate branch or even in the master until you're sure it's ready to be released (code tested, docs updated, etc.).
- Let's maybe take a look at big players and see how they implement swipe and tap events? For example:
https://hammerjs.github.io/recognizer-swipe/
http://hammerjs.github.io/recognizer-tap/

**Comment by kkomelin** [comment]
By the way, you donate link/button in the README doesn't work.

**Comment by darenju** [comment]
From what I see, the problem only happens when you want to start swiping from one of the touch zones.

I will check that.

**Comment by kkomelin** [comment]
Thanks @darenju .
I did `npm install` and then `npm run build` and I got the following error:
```bash
...
> webpack

Hash: 031a4f7f529e55a3926f
Version: webpack 4.17.1
Time: 211ms
Built at: 03/19/2019 2:19:44 PM
 1 asset
Entrypoint app = index.js
[0] ./index.jsx 246 bytes {0} [built] [failed] [1 error]

ERROR in ./index.jsx 506:6
Module parse failed: Unexpected token (506:6)
You may need an appropriate loader to handle this file type.
| 
|     const pageItem = (
>       <FlipPageItem
|         shouldUpdate={activeItem}
|         component={_page}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-flip-page@1.5.6 build: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-flip-page@1.5.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
```

**Comment by darenju** [comment]
Yes, there is definitely something missing here, but it should be in the `package.json` devDependencies... I will check.

**Comment by kkomelin** [comment]
Tested 1.5.7. Thanks. 
Swipe and touch work well together on mobiles, but when I try to swipe over touch zones on desktop it doesn't work.

**Comment by kkomelin** [comment]
Also tested 1.5.7 on iPhone. Touch doesn't work.

**Comment by darenju** [comment]
I am really puzzled as where the problem is coming from... I might need some help to see where the issue is.

The original issue was that page flip on touch zones touch was triggered twice, I deducted it was because of double events `touch`/`mousedown`. Removed the `touch` one, worked, but now it is conflicting with the basic behavior of the component...

**Comment by kkomelin** [comment]
I think we're quite close to the resolution. Just need swipe over touch zones working and Apple Safari supported. 
Anyway, you've done a great job in investigating the issue and trying different solutions. Thanks for that!
