### ISSUE TITLE
how to add a page after component render

### ISSUE THREAD

**Issue by abelvii** [darenju/react-flip-page#99]
hey bro, 
thanks for your work

I want to add page after i get some page, those page are some html code.And it is very large. So i wanna know is there a method to add a page async

**Comment by darenju** [comment]
Hello,

Have you tried something already? There is no reason you could not do some dynamic rendering inside the `FlipPage` component and have it re-render all of the pages. You should hold the current page position in the state of your component to prevent it from going back to the first page when you render the new pages though.

**Comment by abelvii** [comment]
> Hello,
> 
> Have you tried something already? There is no reason you could not do some dynamic rendering inside the `FlipPage` component and have it re-render all of the pages. You should hold the current page position in the state of your component to prevent it from going back to the first page when you render the new pages though.

thanks for your reply!
yeah, I have tried some way that I can imagine,but they are not work, and it is not dynamic rendering, because I have to get html code from back end server.

**Comment by darenju** [comment]
You should store that HTML code in your state.

This way, when you retrieve it, you put it in the state, and the component will re-render because of it. Something like this :

```
render() {
  const { htmlCode } = this.state;

  return (
    <FlipPage>
      <Page1 />
      <Page2 />
      {htmlCode}
    </FlipPage>
  );
}
```

Note that your HTML code should be separate tags for pages to be rendered.

**Comment by abelvii** [comment]
> You should store that HTML code in your state.
> 
> This way, when you retrieve it, you put it in the state, and the component will re-render because of it. Something like this :
> 
> ```
> render() {
>   const { htmlCode } = this.state;
> 
>   return (
>     <FlipPage>
>       <Page1 />
>       <Page2 />
>       {htmlCode}
>     </FlipPage>
>   );
> }
> ```
> Note that your HTML code should be separate tags for pages to be rendered.

thanks for your help, it is help me a lot! :)
